# Generated by Django 2.2.1 on 2019-05-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptosignals', '0002_auto_20190526_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='', max_length=255),
        ),
    ]
