# Generated by Django 2.2.1 on 2019-05-26 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptosignals', '0003_auto_20190526_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='high',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='low',
        ),
    ]
