# Generated by Django 2.2.1 on 2019-05-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptosignals', '0004_auto_20190526_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='channel',
            field=models.CharField(default='', max_length=32),
        ),
    ]
